// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AboutInfo = { version: string, author: string, repository: string, license: string, 
/**
 * Whether this build came out of the project's own release workflow.
 *
 * The release workflow sets `ASTRAIL_OFFICIAL_BUILD` only when it runs in
 * the upstream repository, so a fork that builds the same tag gets `false`
 * without having to remember to change anything — which is what term 2
 * (GPL section 7c, mark modified versions) asks for.
 */
official: boolean, };
