// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlaySettings } from "./OverlaySettings";
import type { ShortcutsSettings } from "./ShortcutsSettings";
import type { UpdateChannel } from "./UpdateChannel";

/**
 * Global settings configured by the user or the app itself.
 */
export type AppSettings = { 
/**
 * Whether the user has completed the first-run onboarding setup.
 */
setup_completed: boolean, 
/**
 * Whether the app hides to the system tray when the main window is closed.
 */
minimize_to_tray: boolean, 
/**
 * In-game metrics overlay configuration.
 */
overlay: OverlaySettings, 
/**
 * Global keybindings for the application.
 */
shortcuts: ShortcutsSettings, 
/**
 * UI language: "system" (follow the OS, fallback English), "es" or "en".
 */
language: string, 
/**
 * Whether to publish the game being played to Discord Rich Presence.
 *
 * Defaults to **off**: this broadcasts what the user is playing to their whole
 * friends list, so it is opt-in. `#[serde(default)]` means an existing
 * settings file without the field also reads as off.
 */
discord_enabled: boolean, 
/**
 * Which releases the updater offers. `beta` is opt-in: those builds reach the
 * stable channel a day or two later, unchanged, if nothing breaks.
 */
update_channel: UpdateChannel, 
/**
 * Whether a library game started outside Astrail (from its store client, a
 * desktop shortcut…) is timed and gets the HUD too. Detection is a foreground
 * window event, not a process poll (see `fgwatch.rs`). On by default, also for
 * a settings file written before the field existed.
 */
track_external_games: boolean, };
