// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a backup file holds, shown before the user confirms the restore.
 */
export type BackupSummary = { file_name: string, created: number, app_version: string, manual_apps: number, played_games: number, favorites: number, hidden: number, categories: number, covers: number, includes_settings: boolean, };
