// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an export wrote, for the settings card.
 */
export type BackupExportReport = { path: string, covers: number, 
/**
 * Covers left out because the file would have grown past its cap.
 */
covers_skipped: number, 
/**
 * Stores that exist but could not be read; they are not in the file.
 */
unreadable: Array<string>, };
