// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a restore did.
 */
export type BackupImportReport = { covers: number, 
/**
 * Where the data that was replaced went.
 */
safety_copy: string, };
