// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-created category, optionally with a chosen icon key (resolved to an
 * SVG on the frontend from a bundled icon set). Persisted in `storage.rs`.
 */
export type Category = { name: string, icon: string | null, };
