// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The answer to "what is the cover for this name?".
 *
 * Three states on purpose. The frontend remembers an answer for the whole
 * session, so "IGDB said there is none" and "IGDB could not be asked" (offline,
 * rate limited, no credentials, a malformed reply) must not look the same: the
 * first is a fact worth remembering, the second has to be asked again.
 */
export type CoverAnswer = { "status": "found", "path": string } | { "status": "not_found" } | { "status": "unavailable" };
