// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayInfo = { name: string, width: number, height: number, refresh_hz: number, primary: boolean, };
