// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What went wrong, in terms the user can act on. Serialized in snake_case; the
 * webview has a translation for each.
 */
export type ErrorCode = "not_found" | "invalid_input" | "autostart_unavailable" | "backup_invalid" | "backup_changed" | "launch_failed" | "io" | "internal";
