// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSource } from "./GameSource";

/**
 * A single launchable entry in the unified library.
 */
export type Game = { 
/**
 * Stable unique id, e.g. "steam:440", "epic:Fortnite", "manual:1718900000000".
 */
id: string, name: string, source: GameSource, 
/**
 * Steam AppID (only for `GameSource::Steam`).
 */
app_id: number | null, 
/**
 * Absolute path to the executable, when the game is launched directly
 * (manual apps, GOG, Xbox, some EA games).
 */
executable: string | null, 
/**
 * Install directory on disk, when known.
 */
install_dir: string | null, 
/**
 * Remote cover image URL. For Steam this is the vertical capsule; for other
 * stores it is resolved lazily via `art.rs` (SteamGridDB / Steam CDN).
 */
cover_url: string | null, 
/**
 * Protocol URI used to launch store-managed games (Epic / Ubisoft), so the
 * store handles DRM/updates/overlay. Takes precedence over `executable`.
 */
launch_uri: string | null, 
/**
 * User overlay: whether the user marked this entry as a favorite. Not set by
 * scanners; applied in `get_library` from `favorites.json` (`storage.rs`).
 */
favorite: boolean, 
/**
 * User overlay: manual categories the user assigned to this entry. Not set by
 * scanners; applied in `get_library` from `categories.json` (`storage.rs`).
 */
categories: Array<string>, };
