// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a library entry comes from. Each variant is produced by its own scanner
 * module (`steam.rs`, `epic.rs`, `gog.rs`, …) and merged in `get_library`.
 */
export type GameSource = "steam" | "epic" | "gog" | "ea" | "ubisoft" | "xbox" | "battlenet" | "riot" | "rockstar" | "amazon" | "battlestate" | "windows" | "app" | "manual";
