// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuKind } from "./GpuKind";

/**
 * A GPU as shown in the panel. `key` ("nvml:<i>" / "pci:<AMD PnP id fragment>") is
 * set only for metric-capable GPUs — those can be picked for the overlay; empty
 * otherwise.
 */
export type GpuInfo = { name: string, vendor: string, vram_mb: number, 
/**
 * The panel translates it.
 */
kind: GpuKind, key: string, };
