// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a GPU is built into the CPU. `Unknown` serializes as `""`, the value
 * the panel has always received when Windows could not tell.
 */
export type GpuKind = "integrated" | "discrete" | "";
