// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the privileged metrics can use in this process, for the settings screen.
 *
 * Each field is a fact the UI turns into advice: FPS through PresentMon needs
 * `etw` (admin *or* Performance Log Users), CPU temperature needs `elevated`
 * *and* `pawnio`. Group membership is fixed at logon; PawnIO can be installed
 * while Astrail runs, so the screen re-asks each time it opens.
 */
export type MetricsAccess = { elevated: boolean, etw: boolean, pawnio: boolean, };
