// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the in-game overlay may be costing performance: the live composition health
 * plus the system-config levers that decide whether Windows grants the HUD a hardware
 * overlay plane (MPO). Surfaced in the overlay settings so the user can fix their config.
 */
export type MpoDiagnostics = { 
/**
 * Live overlay health: 0 unknown, 1 free (HUD on a hardware plane), 2 costing
 * (DWM compositing the HUD → the game loses independent-flip).
 */
health: 0 | 1 | 2, 
/**
 * Number of active monitors. Multi-monitor is the most common MPO blocker.
 */
monitors: number, 
/**
 * Refresh rate (Hz) of each active monitor.
 */
refresh_rates: Array<number>, 
/**
 * True if the active monitors run at different refresh rates — a frequent MPO
 * blocker (DWM can't independent-flip cleanly across mixed refresh).
 */
mixed_refresh: boolean, 
/**
 * Hardware-accelerated GPU scheduling (HAGS) enabled — often required for MPO.
 * `None` if it couldn't be determined.
 */
hags: boolean | null, };
