// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the HUD does when Windows cannot give it a hardware overlay plane.
 */
export type MpoMode = "always" | "performance";
