// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corner of the game's monitor the HUD is drawn in.
 */
export type OverlayPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right";
