// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for the in-game performance/telemetry overlay. Persisted as part
 * of `AppSettings`; applied live by `metrics.rs` and read by the overlay window.
 */
export type OverlaySettings = { 
/**
 * Master switch. When off, the sampler idles and the overlay window stays hidden.
 */
enabled: boolean, 
/**
 * Corner of the screen: "top-left" | "top-right" | "bottom-left" | "bottom-right".
 */
position: "top-left" | "top-right" | "bottom-left" | "bottom-right", 
/**
 * Sampling/emit interval in milliseconds.
 */
interval_ms: number, show_fps: boolean, show_frametime: boolean, 
/**
 * 1 % / 0.1 % low FPS. PresentMon only; the rows appear once there are enough
 * frames to back them.
 */
show_lows: boolean, 
/**
 * Frametime graph under the rows. Off by default: it takes room, and it makes
 * the HUD redraw on every tick instead of only when a number changes.
 */
show_frametime_graph: boolean, 
/**
 * Share of the game's frame time its GPU work took (PresentMon `msGPUActive`).
 * Off by default: not every driver reports it, and the row is only drawn while
 * every frame in the window carries a reading.
 */
show_gpu_busy: boolean, show_gpu: boolean, show_gpu_temp: boolean, 
/**
 * CPU temperature (needs the LHM sidecar + admin). Off by default since it
 * requires elevation; users opt in.
 */
show_cpu_temp: boolean, show_vram: boolean, show_cpu: boolean, show_ram: boolean, 
/**
 * Which GPU to sample: "auto" | "nvml:<i>" | "pci:<AMD PnP id fragment>".
 */
gpu: string, 
/**
 * Color of metric labels ("FPS", "GPU"…). CSS hex color.
 */
label_color: string, 
/**
 * Color of metric values (numbers). CSS hex color.
 */
value_color: string, 
/**
 * Accent color for FPS, GPU%, CPU% and the game title. CSS hex color.
 */
accent_color: string, 
/**
 * Background opacity of the HUD panel, 0–100.
 */
bg_opacity: number, 
/**
 * Font-size key: "xs" | "sm" | "base".
 */
font_size: string, 
/**
 * What to do when the HUD can't get a hardware overlay plane and DWM has to
 * composite it (which drops the game out of independent-flip → FPS/latency cost):
 * "always" (draw regardless — current behavior) | "performance" (auto-hide the HUD
 * once a stable *composed* state is detected, so it never silently costs FPS).
 */
mpo_mode: "always" | "performance", };
