// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";

/**
 * Accumulated play stats for one game, keyed by `Game.id`.
 */
export type PlayStat = { 
/**
 * Total seconds played (cached sum of `history`).
 */
seconds: number, 
/**
 * Unix timestamp of the last session end, if ever played.
 */
last_played: number | null, 
/**
 * Full per-session history (newest appended last).
 */
history: Array<Session>, };
