// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was measured during one play session. Every figure is optional: FPS needs
 * PresentMon (administrator), CPU temperature needs the sensor sidecar.
 */
export type SessionPerf = { 
/**
 * Frames presented divided by the time they took, not a mean of FPS readings.
 */
avg_fps?: number | null, 
/**
 * FPS of the frametime 99 % of the session's frames beat.
 */
low_1_fps?: number | null, 
/**
 * Seconds of frames behind the two figures above.
 */
fps_secs?: number | null, max_gpu_temp_c?: number | null, max_cpu_temp_c?: number | null, };
