// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionPerf } from "./SessionPerf";

/**
 * One finished play session.
 */
export type Session = { start: number, end: number, 
/**
 * What the HUD measured during the session, if it measured anything (see
 * `sessionperf`). Absent in sessions recorded before this existed, in sessions
 * played with the overlay off, and in sessions recovered after a crash.
 */
perf?: SessionPerf | null, };
