// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SteamPlaytime = { 
/**
 * Minutes, as Steam stores them. Never 0: an unplayed app is reported as absent.
 */
minutes: number, 
/**
 * Unix seconds of the last launch Steam knows about.
 */
last_played: number | null, };
