// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskInfo } from "./DiskInfo";
import type { DisplayInfo } from "./DisplayInfo";
import type { GpuInfo } from "./GpuInfo";

export type SystemInfo = { cpu: string | null, cpu_cores: number, cpu_threads: number, ram_total_mb: number, os: string | null, motherboard: string | null, gpus: Array<GpuInfo>, disks: Array<DiskInfo>, displays: Array<DisplayInfo>, };
