// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Release channel followed by the updater (see `updates.rs`).
 */
export type UpdateChannel = "stable" | "beta";
