// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateChannel } from "./UpdateChannel";

/**
 * Same shape as the updater plugin's own metadata (the JavaScript `Update` class
 * is built from it), plus the channel the offer came from.
 */
export type UpdateOffer = { rid: number, currentVersion: string, version: string, date?: string, body?: string, rawJson: Record<string, unknown>, channel: UpdateChannel, };
